export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as ErrorPage } from "./ErrorPage";
export { default as Stations } from "./Stations";
export { default as Users } from "./Users";
export { default as Ltds } from "./Ltds";
export { default as Banks } from "./Banks";
export { default as Chillers } from "./Chillers";
export { default as Osushka } from "./Osushka";
export { default as Dispensers } from "./Dispensers";
export { default as Compressors } from "./Compressors";
export { default as TypeOfCompressors } from "./TypeOfCompressors";
export { default as TypeOfDispensers } from "./TypeOfDispensers";
export { default as TypeOfOsushka } from "./TypeOfOsushka";
export { default as TypeOfChillers } from "./TypeOfChillers";
export { default as EquipmentTypes } from "./EquipmentTypes";
export { default as Regions } from "./Regions";
export { default as Cities } from "./Cities";
export { default as Employees } from "./Employees";
export { default as DocPerpetual } from "./DocPerpetual";
export { default as DocDeadline } from "./DocDeadline";
export { default as DocByStation } from "./DocByStation";
export { default as DocDeadlineInf } from "./DocDeadlineInf";
export { default as DocByStationInf } from "./DocByStationInf";
export { default as StationDocs } from "./StationDocs";
export { default as DocumentTypePage } from "./DocumentTypePage";
export { default as DocumentPageInf } from "./DocumentPageInf";
export { default as StationDocsInf } from "./StationDocsInf";
export { default as Partners } from "./Partners";
export { default as PartnersList } from "./PartnersList";
export { default as HomeBooker } from "./HomeBooker";
export { default as HomeOperator } from "./HomeOperator";
export { default as GeneralDailyReport } from "./GeneralDailyReport";
export { default as DailyHoseReport } from "./DailyHoseReport";
export { default as DailyReportPartners } from "./DailyReportPartners";
export { default as EmployeesDocDeadlineInf } from "./EmployeesDocDeadlineInf";
export { default as EmployeesDocDeadline } from "./EmployeesDocDeadline";
export { default as ControlPayments } from "./ControlPayments";
export { default as Payments } from "./Payments";
export { default as ReportOnDebtsPartners } from "./ReportOnDebtsPartners";

// export { default as License } from "./documents/License";
// export { default as GasCertificate } from "./documents/GasCertificate";
// export { default as GasAnalyzer } from "./documents/GasAnalyzer";
// export { default as MoistureMeter } from "./documents/MoistureMeter";
// export { default as ElectricalMeters } from "./documents/ElectricalMeters";
// export { default as Thermometers } from "./documents/Thermometers";
// export { default as Manometers } from "./documents/Manometers";
// export { default as GasUnit } from "./documents/GasUnit";
// export { default as Autopilot } from "./documents/Autopilot";
// export { default as FlowDevice } from "./documents/FlowDevice";
// export { default as ElectricityMeter } from "./documents/ElectricityMeter";
// export { default as WaterMeter } from "./documents/WaterMeter";
// export { default as InsuranceProd } from "./documents/InsuranceProd";
// export { default as Insurance } from "./documents/Insurance";
// export { default as EcologyEmission } from "./documents/EcologyEmission";
// export { default as EcologyGarbage } from "./documents/EcologyGarbage";
// export { default as StudyProtocol } from "./documents/StudyProtocol";
// export { default as HoseTestReport } from "./documents/HoseTestReport";
// export { default as ValveTestReport } from "./documents/ValveTestReport";
// export { default as ElectricalTestReport } from "./documents/ElectricalTestReport";
// export { default as TestReportElecProtec } from "./documents/TestReportElecProtec";
// export { default as ActLubricateTech } from "./documents/ActLubricateTech";
// export { default as TechLeacageTestReport } from "./documents/TechLeacageTestReport";
// export { default as AidKitCheckReport } from "./documents/AidKitCheckReport";
